{
 "title": "San Juan: Monitoreo Integral de Infraestructura (SSJ)",
 "tags": [
  "milicic",
  "sanjuan",
  "ssj",
  "infraestructura",
  "sucursales"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "device_type",
    "label": "Tipo de Dispositivo",
    "query": "Todos : .*, Red y Conectividad : (SSJ-CORE01|SSJ-SWADM|FTG_ar-ssj-predio_SNMP), Virtualización : (SSJ-HPV01), Almacenamiento y Respaldo : (SSJ-BKP01|SSJ-FIL01|SSJ-NAS01), Servidores y Servicios : (SSJ-DCO01|SSJ-SVC01)"
   },
   {
    "name": "host",
    "label": "Dispositivo Específico",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Core Switch (SSJ-CORE01)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-CORE01" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Switch Adm (SSJ-SWADM)",
   "type": "stat",
   "gridPos": { "x": 3, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-SWADM" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hyper-V Físico (SSJ-HPV01)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-HPV01" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Veeam BKP (SSJ-BKP01)",
   "type": "stat",
   "gridPos": { "x": 9, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-BKP01" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "File Server (SSJ-FIL01)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-FIL01" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "QNAP NAS (SSJ-NAS01)",
   "type": "stat",
   "gridPos": { "x": 15, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-NAS01" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Domain Controller (SSJ-DCO01)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-DCO01" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Servicios/Print (SSJ-SVC01)",
   "type": "stat",
   "gridPos": { "x": 21, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-SVC01" },
     "item": { "filter": "Zabbix agent ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Latencia y RTT de Enlace a Dispositivos San Juan (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 14, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "/${device_type:raw}/" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Pérdida de Paquetes en Enlaces de San Juan (%)",
   "type": "timeseries",
   "gridPos": { "x": 14, "y": 4, "w": 10, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "/${device_type:raw}/" },
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Consumo de Cómputo CPU (%) - Servidores San Juan",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "/${device_type:raw}/" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Saturación de Memoria RAM (%) - Servidores San Juan",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "/${device_type:raw}/" },
     "item": { "filter": "Memory utilization" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Particiones de Datos, Respaldo y VMs (D:, E:, F:) - San Juan",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 19, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-HPV01" },
     "item": {
      "filter": "/FS \\[DATA\\(D:\\)\\]: Space: Used, in %/"
     },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-FIL01" },
     "item": {
      "filter": "/FS \\[DATOS\\(E:\\)\\]: Space: Used, in %/"
     },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "SSJ-BKP01" },
     "item": {
      "filter": "/FS \\[DATA-BKP\\(F:\\)\\]: Space: Used, in %/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Volúmenes de Sistema Operativo C: (%) - San Juan",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 19, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "schema": 12,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "/${device_type:raw}/" },
     "item": {
      "filter": "/FS \\[\\(C:\\)\\]: Space: Used, in %/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Incidentes y Alarmas Activas en Localidad San Juan (Zabbix Triggers)",
   "type": "table",
   "gridPos": { "x": 0, "y": 26, "w": 24, "h": 7 },
   "targets": [
    {
     "schema": 12,
     "mode": 4,
     "group": { "filter": "sanJuan" },
     "host": { "filter": "/${device_type:raw}/" },
     "showProblems": "problems",
     "options": {
      "acknowledged": 2,
      "minSeverity": 1,
      "hostsInMaintenance": false
     }
    }
   ]
  }
 ]
}